In [23]:
import numpy as np
from numpy.linalg import inv
import copy

In [2]:
# La fonction donnee
def f(x):
    return (x[0]-5)**2 + (x[1] - 1)**2 + (x[2]+2)**2

In [8]:
# Gradient de la fonction (Градиент функции f)
def gradf(f,x,h = 1e-5):
    df = []
    n = len(x) # Nombre de variable
    
    for i in range(n):
        x_tmp = copy.copy(x)
        x_tmp[i] += h
        dfi = (f(x_tmp) - f(x)) / h
        df.append(dfi)
    return np.array(df)

In [20]:
gradf(f,x=[0,0,0])

array([-9.99999, -1.99999,  4.00001])

In [32]:
# Matrice de Hess (matrice des derivees secondes)
def Hess(f,x,h=1e-3):
    d2f = []
    n = len(x) # Nombre de variable
    
    for i in range(n):
        x_tmp = copy.copy(x)
        x_tmp[i] += h
        
        dfxh = gradf(f,x_tmp)
        dfx = gradf(f,x)
        
        d2f_i = (dfxh - dfx) / h
        d2f.append(d2f_i)
        
    return np.array(d2f)

In [33]:
# Example: Matrice de Hess de f au point [0,0,0]
Hess(f,x=[0,0,0])

array([[2.00000017, 0.        , 0.        ],
       [0.        , 2.00000017, 0.        ],
       [0.        , 0.        , 2.00000017]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
def marquardt(f, x0=[0,0,0], eps=0.1, mu_0=2.0, kmax=5):
    n = len(x0)
    k = 0
    xk = np.array(x0)
    mu_k = mu_0
    
    while True:
        gradient = gradf(f,xk) # step 02
        
        if np.sqrt(np.sum(gradient**2))  < eps: # step 03
            return xk, f(xk)
        
        go_to_step_05 = True
        E = np.eye(n) # Matrice identite
        while go_to_step_05:
            Hk = Hess(f,xk) # step 04
            x_prev = copy.copy(xk)
            xk = xk - np.dot(inv(Hk + mu_k * E), gradient) # step 05
        
            if f(xk) < f(x_prev): # step 06
                mu_k = mu_k / 2
                go_to_step_05 = False
            else:
                mu_k *= 2
        # STEP 07
        k += 1
        if k == kmax:
            return xk, f(xk)

In [36]:
xmin, fmin = marquardt(f,x0=[2,2,-1])
print("xmin: ",xmin)
print("fmin: ", fmin)

xmin:  [ 4.99981645  1.00034478 -2.00212356]
fmin:  4.662057775748831e-06
